export const GET_USERS = 'GET_USERS';
export const REGISTER_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const USERS_LOADING = 'USERS_LOADING';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';