// <auto-generated />
using appIdiomas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace appIdiomas.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("appIdiomas.Models.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AdicionadoEm");

                    b.Property<string>("Description");

                    b.Property<bool>("FotoPrincipal");

                    b.Property<int>("GrupoId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("appIdiomas.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cidade");

                    b.Property<int>("CodigoUsuarioLider");

                    b.Property<string>("Descricao");

                    b.Property<string>("Estado");

                    b.Property<int>("Nivel");

                    b.Property<string>("Nome");

                    b.Property<int>("QuantidadeMembrosAtual");

                    b.Property<int>("QuantidadeMembrosMaxima");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("appIdiomas.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cidade");

                    b.Property<DateTime?>("CriadoEm");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Email");

                    b.Property<string>("Estado");

                    b.Property<string>("Genero");

                    b.Property<string>("Nome");

                    b.Property<string>("Pais");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<DateTime?>("VistoEm");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("appIdiomas.Models.UsuariosGrupos", b =>
                {
                    b.Property<int>("UsuarioId");

                    b.Property<int>("GrupoId");

                    b.HasKey("UsuarioId", "GrupoId");

                    b.HasIndex("GrupoId");

                    b.ToTable("UsuariosGrupos");
                });

            modelBuilder.Entity("appIdiomas.Models.Foto", b =>
                {
                    b.HasOne("appIdiomas.Models.Grupo", "Grupo")
                        .WithMany("Fotos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("appIdiomas.Models.UsuariosGrupos", b =>
                {
                    b.HasOne("appIdiomas.Models.Grupo", "Grupo")
                        .WithMany("UsuariosGrupos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("appIdiomas.Models.Usuario", "Usuario")
                        .WithMany("UsuariosGrupos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
